### ISSUE TITLE
Eslint plugins in local node_modules

### ISSUE THREAD

**Issue by yedidyak** [rizowski/eslint-watch#107]
Hi,

In my project, the .eslintrc file is used across projects, and so is in a dependency. It references other custom lint configs and plugins, all peer dependencies.

If I use `esw -c node_modules/#DEPENDENCY/.eslintrc --color src --watch` it runs fine. However, as soon as a file changes, I get this:

```
Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'
Referenced from: xo-react/space
Referenced from: ##CUSTOM RULE##
Referenced from: ##PROJECT_PATH##/node_modules/##DEPENDENCY##/.eslintrc
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.load (~/.nvm/versions/node/v6.7.0/lib/node_modules/eslint/lib/config/plugins.js:129:26)
    at Array.forEach (native)
    at Object.loadAll (~/.nvm/versions/node/v6.7.0/lib/node_modules/eslint/lib/config/plugins.js:151:21)
    at load (~/.nvm/versions/node/v6.7.0/lib/node_modules/eslint/lib/config/config-file.js:511:21)
    at configExtends.reduceRight.e (~/.nvm/versions/node/v6.7.0/lib/node_modules/eslint/lib/config/config-file.js:391:36)
    at Array.reduceRight (native)
```

If I install all the plugins to the global node_modules, it works. It seems to only find relatively referenced plugins on the initial pass, and not on any subsequent watcher passes.

**Comment by FWoelffel** [comment]
Shouldn't this be considered a bug?

**Comment by rizowski** [comment]
@FWoelffel since the issue was closed by @yedidyak  in less than 10 minutes I figured it wasn't a bug.

**Comment by rizowski** [comment]
@FWoelffel can you send me the debug logs?
`DEBUG=esw:* esw ...`

**Comment by FWoelffel** [comment]
First:
```
$ node -v  && npm -v && which esw 
v6.10.0
4.5.0
/home/fwoelffel/.nvm/versions/node/v6.10.0/bin/esw
```

(eslint-watch is globally installed and eslint is locally installed.)

Here is my command line:
```
$ esw -w --ignore-pattern node_modules --ignore-pattern http --ignore-pattern jsdoc --ignore-pattern apidoc --fix api services configuration bootstrap.js
```
and the ouput:
```
  esw:internal-settings Eslint installed locally node_modules/.bin/eslint +0ms
  esw:internal-settings { eslintPath: 'node_modules/.bin/eslint',
  esw:internal-settings   platform: 'linux',
  esw:internal-settings   isWindows: false } +2ms
  esw:eslint-cli Loaded +38ms
  esw:eslint-help Loaded +14ms
  esw:options Loaded +0ms
  esw:eslint-help Executing help +0ms
  esw:eslint-cli eslint: '--help' +1ms
  esw:executor node_modules/.bin/eslint [ '--help' ] +1ms
  esw:eslint-cli { exitCode: 0,
  esw:eslint-cli   message: 'eslint [options] file.js [file.js] [dir]\n\nBasic configuration:\n  -c, --config path::String    Use configuration from this file or shareable config\n  --no-eslintrc                Disable use of configuration from .eslintrc\n  --env [String]               Specify environments\n  --ext [String]               Specify JavaScript file extensions - default: .js\n  --global [String]            Define global variables\n  --parser String              Specify the parser to be used\n  --parser-options Object      Specify parser options\n\nCaching:\n  --cache                      Only check changed files - default: false\n  --cache-file path::String    Path to the cache file. Deprecated: use --cache-location - default: .eslintcache\n  --cache-location path::String  Path to the cache file or directory\n\nSpecifying rules and plugins:\n  --rulesdir [path::String]    Use additional rules from this directory\n  --plugin [String]            Specify plugins\n  --rule Object                Specify rules\n\nIgnoring files:\n  --ignore-path path::String   Specify path of ignore file\n  --no-ignore                  Disable use of ignore files and patterns\n  --ignore-pattern [String]    Pattern of files to ignore (in addition to those in .eslintignore)\n\nUsing stdin:\n  --stdin                      Lint code provided on <STDIN> - default: false\n  --stdin-filename String      Specify filename to process STDIN as\n\nHandling warnings:\n  --quiet                      Report errors only - default: false\n  --max-warnings Int           Number of warnings to trigger nonzero exit code - default: -1\n\nOutput:\n  -o, --output-file path::String  Specify file to write report to\n  -f, --format String          Use a specific output format - default: stylish\n  --color, --no-color          Force enabling/disabling of color\n\nMiscellaneous:\n  --init                       Run config initialization wizard - default: false\n  --fix                        Automatically fix problems\n  --debug                      Output debugging information\n  -h, --help                   Show help\n  -v, --version                Output the version number\n  --no-inline-config           Prevent comments from changing config or rules\n  --print-config path::String  Print the configuration for the given file\n' } +177ms
  esw:eslint-help Alias found: -c +1ms
  esw:eslint-help Parsing --config +1ms
  esw:eslint-help Parsing --no-eslintrc +0ms
  esw:eslint-help Parsing no option --no-eslintrc +0ms
  esw:eslint-help Parsing --env +0ms
  esw:eslint-help Parsing --ext +1ms
  esw:eslint-help Parsing --global +0ms
  esw:eslint-help Parsing --parser +0ms
  esw:eslint-help Parsing --parser-options +0ms
  esw:eslint-help Parsing --cache +0ms
  esw:eslint-help Parsing --cache-file +0ms
  esw:eslint-help Parsing --cache-location +0ms
  esw:eslint-help Parsing --rulesdir +0ms
  esw:eslint-help Parsing --plugin +0ms
  esw:eslint-help Parsing --rule +0ms
  esw:eslint-help Parsing --ignore-path +0ms
  esw:eslint-help Parsing --no-ignore +0ms
  esw:eslint-help Parsing no option --no-ignore +0ms
  esw:eslint-help Parsing --ignore-pattern +0ms
  esw:eslint-help Parsing --stdin +0ms
  esw:eslint-help Parsing --stdin-filename +0ms
  esw:eslint-help Parsing --quiet +0ms
  esw:eslint-help Parsing --max-warnings +0ms
  esw:eslint-help Alias found: -o +0ms
  esw:eslint-help Parsing --output-file +1ms
  esw:eslint-help Alias found: -f +0ms
  esw:eslint-help Parsing --format +0ms
  esw:eslint-help Parsing --init +0ms
  esw:eslint-help Parsing --fix +0ms
  esw:eslint-help Parsing --debug +0ms
  esw:eslint-help Alias found: -h +1ms
  esw:eslint-help Parsing --help +0ms
  esw:eslint-help Alias found: -v +0ms
  esw:eslint-help Parsing --version +0ms
  esw:eslint-help Parsing --no-inline-config +0ms
  esw:eslint-help Parsing no option --no-inline-config +0ms
  esw:eslint-help Parsing --print-config +0ms
Error: Cannot find module 'eslint'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/fwoelffel/.nvm/versions/node/v6.10.0/lib/node_modules/eslint-watch/src/watcher.js:2:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

Yesterday I had eslint globally and locally. It looked like the first pass was using the locally installed eslint and the next passes were using the globally eslint which wasn't itself able to find a eslint rules module locally installed.

**Comment by rizowski** [comment]
@FWoelffel I will investigate the issue. Might take me a bit. But if you end up figuring it out I am always open to PRs. I try to address any PRs as quickly as possible.

**Comment by mdshoeb01** [comment]
Similar kind of issue i am facing, It runs only on first call.
Then it says 
/usr/local/lib/node_modules/eslint/lib/util/module-resolver.js:72
            throw new Error(`Cannot find module '${name}'`);
                  ^
Error: Cannot find module 'eslint-config-airbnb-base'
Referenced from: /home/shoeb/Documents/shoeb/mountblue/06-mohammed-webapplication/.eslintrc.js

any help would be highly appreciated

**Comment by rizowski** [comment]
@yedidyak @fwoelffel @mdshoeb01 Can one of you test in V5 of eslint-watch if this is still a concern. I've changed how esw ends up trying to find eslint.

**Comment by mdshoeb01** [comment]
@rizowski The project which i was working is completed.
Now, when i tried to test it with older version of eslint-watch, It worked, So probably it might be the issue with other dependent packages or their versions.
Btw i can see that you have removed colors in latest version, but they were good.
