### ISSUE TITLE
Intermittent errors

### ISSUE THREAD

**Issue by davestewart** [rizowski/eslint-watch#119]
### Environment

  - Node Version: 6.11.0
  - Eslint-Watch Version: 3.1.0
  - Eslint Version: 3.19.0

### Basic Description of the problem

I run your plugin , but when I save a file, I get the following error, intermittently (1 out of every 2 saves) :

```
/Users/davestewart/Sites/dev/vue-element/node_modules/eslint-watch/src/formatters/simple-detail.js:29
  results.forEach(function (result) {
          ^
TypeError: Cannot read property 'length' of undefined
    at /Users/davestewart/Sites/dev/vue-element/node_modules/eslint-watch/src/formatters/simple-detail.js:33:10
    at Array.forEach (native)
    at simpleDetail (/Users/davestewart/Sites/dev/vue-element/node_modules/eslint-watch/src/formatters/simple-detail.js:29:11)
    at lintFile (/Users/davestewart/Sites/dev/vue-element/node_modules/eslint-watch/src/watcher.js:92:16)
    at FSWatcher.changeEvent (/Users/davestewart/Sites/dev/vue-element/node_modules/eslint-watch/src/watcher.js:111:9)
    at emitOne (events.js:96:13)
    at FSWatcher.emit (events.js:188:7)
    at FSWatcher.<anonymous> (/Users/davestewart/Sites/dev/vue-element/node_modules/chokidar/index.js:196:15)
    at FSWatcher._emit (/Users/davestewart/Sites/dev/vue-element/node_modules/chokidar/index.js:238:5)
    at FSWatcher.<anonymous> (/Users/davestewart/Sites/dev/vue-element/node_modules/chokidar/lib/fsevents-handler.js:204:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Vue-Element-Starter@1.0.0 lintw: `esw client/* -w --ext .js --ext .vue --quiet`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Vue-Element-Starter@1.0.0 lintw script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/davestewart/.npm/_logs/2017-06-14T10_41_03_258Z-debug.log

```
### How to reproduce it

  1. Command: `esw client/* -w --ext .js --ext .vue --quiet`
  2. Save file
  3. Watch crashes

### More info

Since writing this, strangely, the bug has now stopped (I was having it all morning, and haven't worked on it since).

But the problem seemed to be `results` being null in your code.

Any ideas? I don't want to waste your time on this, but I am curious, as it was a real thing 😮

**Comment by rizowski** [comment]
@davestewart Thanks for posting this but unfortunately I don't have enough information to debug this issue. Please provide the information detailed in the [Issue Template](https://github.com/rizowski/eslint-watch/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by davestewart** [comment]
I've updated the original ticket :)

**Comment by rizowski** [comment]
@davestewart There could be some defensive coding done around the simple-detail-formatter so that way this error isn't what is displayed. But I am wondering if this issue is related to #115. Either way, I am glad it is working for you now. :) I'll keep this issue in mind as I make the fixes for #115

**Comment by vukan71** [comment]
Hi,

I have same issue:
using:  `esw --quiet --watch .`

on first run everything is ok, and after second change in file I get following error: 

C:\...\node_modules\eslint-watch\src\formatters\simple-detail.js:29
  results.forEach(function (result) {
          ^
TypeError: Cannot read property 'length' of undefined
    at C:\...\node_modules\eslint-watch\src\formatters\simple-detail.js:33:10
    at Array.forEach (native)
    at simpleDetail (C:\...\node_modules\eslint-watch\src\formatters\simple-detail.js:29:11)
    at lintFile (C:\...\node_modules\eslint-watch\src\watcher.js:92:16)
    at FSWatcher.changeEvent (C:\...\node_modules\eslint-watch\src\watcher.js:111:9)
    at emitTwo (events.js:106:13)
    at FSWatcher.emit (events.js:191:7)
    at FSWatcher.<anonymous> (C:\...\node_modules\chokidar\index.js:196:15)
    at FSWatcher._emit (C:\...\node_modules\chokidar\index.js:238:5)
    at FSWatcher.NodeFsHandler._handleFile (C:\...e\node_modules\chokidar\lib\nodefs-handler.js:275:10)

**Comment by rizowski** [comment]
This should be fixed in the latest release.
