### ISSUE TITLE
esw --watch throws EPERM on Windows

### ISSUE THREAD

**Issue by XuYan** [rizowski/eslint-watch#137]
### Environment

  - Node Version: v9.4.0
  - Eslint-Watch Version: v4.19.1
  - Eslint Version: v4.19.1

### Basic Description of the problem
Run eslint-watch on a single file on Windows throws an EPERM exception

### How to reproduce it
1. Command: `esw --watch client/errors.js`

### Debug output:

```
✓ Clean (16:00:23)

{ Error: watch client/errors.js EPERM
    at _errnoException (util.js:1003:13)
    at FSWatcher.start (fs.js:1397:19)
    at Object.fs.watch (fs.js:1423:11)
    at createFsWatchInstance (/mnt/e/IRIS/IRIS/Iris.Cloud/Iris.Web.Portal/node_modules/eslint-watch/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/mnt/e/IRIS/IRIS/Iris.Cloud/Iris.Web.Portal/node_modules/eslint-watch/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/mnt/e/IRIS/IRIS/Iris.Cloud/Iris.Web.Portal/node_modules/eslint-watch/node_modules/chokidar/lib/nodefs-handler.js:229:14)
    at FSWatcher.NodeFsHandler._handleFile (/mnt/e/IRIS/IRIS/Iris.Cloud/Iris.Web.Portal/node_modules/eslint-watch/node_modules/chokidar/lib/nodefs-handler.js:256:21)
    at FSWatcher.<anonymous> (/mnt/e/IRIS/IRIS/Iris.Cloud/Iris.Web.Portal/node_modules/eslint-watch/node_modules/chokidar/lib/nodefs-handler.js:474:21)
    at FSReqWrap.oncomplete (fs.js:167:5)
  errno: 'EPERM',
  code: 'EPERM',
  syscall: 'watch client/errors.js',
  filename: 'client/errors.js' }
```

**Comment by XuYan** [comment]
Thank you for your reply, rizowski!
Just checked, the same exception is thrown on latest node v9.11.1 as well :(

**Comment by rizowski** [comment]
@XuYan Is this still an issue? I noticed that it was being ran in the Windows linux subsystem. Which microsoft has recently changed quite a bit around file system permissions by passing along metadata on mount.

**Comment by rizowski** [comment]
Closing this for now. If this is still an issue I am willing to reopen to discuss.
