### ISSUE TITLE
Missing Module

### ISSUE THREAD

**Issue by aedryan** [rizowski/eslint-watch#158]
### Environment

  - Node Version: 10.14.2
  - Eslint-Watch Version: 5.1.0
  - Eslint Version: 5.16.0

### Basic Description of the problem

When running eslint watch I get an error about a missing module:
```
Error: Cannot find module 'lodash.debounce'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\repositories\silk-react-components\node_modules\eslint-watch\src\events\watch\index.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```
I believe [this dev dependency](https://github.com/rizowski/eslint-watch/blame/master/package.json#L108) needs to be in dependencies.

### How to reproduce it

  1. Command: `esw path/to/some/js`

**Comment by rizowski** [comment]
I'll have a fix out shortly. I immediately published out a fix but I think something went wrong with the publish for v5.1.1. v5.1.2 will be the corrected version.

**Comment by rizowski** [comment]
v5.1.2 is now published. This should now be fixed. Sorry for the inconvenience.

**Comment by aedryan** [comment]
Thanks for the quick fix!
